#include "WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework.h"
	CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__App* CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework__App;
	CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global* CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework__Global;
// public.
	CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework() {

	}
	CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::~WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework__App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework__Global;
	}
	void CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework();
	}
	void CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global();
	}
	CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__App* CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__App();
	}
	CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global* CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global();
	}
	void CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global();
	}
	void CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__App();
	}
	void CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global();
	}
// private.
	void CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework__App = nullptr;
	}
	void CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework__Global = nullptr;
	}
	void CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework__App = new class CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__App() == nullptr) {}
	}
	void CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework__Global = new class CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global() == nullptr) {}
	}
	CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__App* CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework__App;
	}
	CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global* CLIBWriteQueAtClient_LaunchQueConditionCode::WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_Client_LaunchQueConditionCode__Framework__Global;
	}