#include "WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework.h"
CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__App* CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::_stat_CLASS_get_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework__App;
	CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Global* CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::_stat_CLASS_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework__Global;
// public.
	CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework() {

	}
	CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::~WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework() {
		delete _stat_CLASS_get_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework__App;
		delete _stat_CLASS_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework__Global;
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::dyn_CLASS_create_Architecture() {
		stat_CLASS_boot1_DEFINE_WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework();
		stat_CLASS_boot3_INITIALISE_WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework();
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::dyn_CLASS_create_CLIB_OpenEpiCentre_Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteQueForThreadsAt_END_LaunchQueConditionCode__Global();
		stat_CLASS_boot3_INITIALISE_WriteQueForThreadsAt_END_LaunchQueConditionCode__Global();
	}
	CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__App* CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::dyn_CLASS_get_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__App() {
		return stat_CLASS_get_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__App();
	}
	CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Global* CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::dyn_CLASS_get_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__Global() {
		return stat_CLASS_get_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__Global();
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework() {
		stat_CLASS_boot1_DEFINE_WriteQueForThreadsAt_END_LaunchQueConditionCode__App();
		stat_CLASS_boot1_DEFINE_WriteQueForThreadsAt_END_LaunchQueConditionCode__Global();
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteQueForThreadsAt_END_LaunchQueConditionCode__App();
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteQueForThreadsAt_END_LaunchQueConditionCode__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteQueForThreadsAt_END_LaunchQueConditionCode__Global();
	}
// private.
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteQueForThreadsAt_END_LaunchQueConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework__App = nullptr;
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteQueForThreadsAt_END_LaunchQueConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework__Global = nullptr;
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteQueForThreadsAt_END_LaunchQueConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework__App = new class CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__App();
		while (stat_CLASS_get_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__App() == nullptr) {}
	}
	void CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::pr_stat_CLASS_boot3_INITIALISE_WriteQueForThreadsAt_END_LaunchQueConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework__Global = new class CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Global();
		while (stat_CLASS_get_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__Global() == nullptr) {}
	}
	CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__App* CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_get_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__App()
	{
		return _stat_CLASS_get_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework__App;
	}
	CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Global* CLIBWriteQueAtServerLaunchQue_ConditionCode::WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_get_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__Global()
		{
			return _stat_CLASS_ptr_WriteQueForThreadsAt_END_LaunchQueConditionCode__Framework__Global;
		}