#include "WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework.h"
	CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__App* CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework__App;
	CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global* CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework__Global;
// public.
	CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework() {

	}
	CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::~WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework__App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework__Global;
	}
	void CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework();
	}
	void CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global();
	}
	CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__App* CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__App();
	}
	CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global* CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global();
	}
	void CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_END_LaunchQueConditionCode__App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global();
	}
	void CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_END_LaunchQueConditionCode__App();
	}
	void CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global();
	}
// private.
	void CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_END_LaunchQueConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework__App = nullptr;
	}
	void CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework__Global = nullptr;
	}
	void CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_END_LaunchQueConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework__App = new class CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__App() == nullptr) {}
	}
	void CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework__Global = new class CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global() == nullptr) {}
	}
	CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__App* CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework__App;
	}
	CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global* CLIBWriteQueAtEND_LaunchQueConditionCode::WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_END_LaunchQueConditionCode__Framework__Global;
	}