#include "../include/WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework.h"
	CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__App* CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework__App;
	CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global* CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::_stat_CLASS_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework__Global;
// public.
	CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework() {

	}
	CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::~WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework() {
		delete _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework__App;
		delete _stat_CLASS_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework__Global;
	}
	void CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Architecture() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework();
	}
	void CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::dyn_CLASS_create_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global_and_Settings()
	{
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global();
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global();
	}
	CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__App* CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__App() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__App();
	}
	CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global* CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::dyn_CLASS_get_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global() {
		return stat_CLASS_get_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global();
	}
	void CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework() {
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__App();
		stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global();
	}
	void CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework() {
		stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__App();
	}
	void CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global() {
		pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global();
	}
// private.
	void CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework__App = nullptr;
	}
	void CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::stat_CLASS_boot1_DEFINE_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework__Global = nullptr;
	}
	void CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__App()
	{
		_stat_CLASS_get_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework__App = new class CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__App();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__App() == nullptr) {}
	}
	void CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::pr_stat_CLASS_boot3_INITIALISE_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global()
	{
		_stat_CLASS_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework__Global = new class CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global();
		while (stat_CLASS_get_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global() == nullptr) {}
	}
	CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__App* CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__App()
	{
		return _stat_CLASS_get_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework__App;
	}
	CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global* CLIBWriteQueAt_ENDS_LaunchQueConditionCode::WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework::stat_CLASS_get_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Global()
	{
		return _stat_CLASS_ptr_WriteEnableForThreadsAt_ENDS_LaunchQueConditionCode__Framework__Global;
	}